"""
models.py — SQLAlchemy ORM models for Phase 3.
"""

from datetime import datetime, timezone

from sqlalchemy import (
    Column,
    Integer,
    String,
    DateTime,
    ForeignKey,
    UniqueConstraint,
    Float,
)
from sqlalchemy.orm import relationship

from database import Base


# ── Seller ───────────────────────────────────────────────────────────────────

class Seller(Base):
    __tablename__ = "sellers"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    account_age_days = Column(Integer, nullable=False, default=0)
    trust_score = Column(Integer, nullable=False, default=100)

    products = relationship("Product", back_populates="seller")
    complaints = relationship("Complaint", back_populates="seller")


# ── Buyer ────────────────────────────────────────────────────────────────────

class Buyer(Base):
    __tablename__ = "buyers"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    credibility_score = Column(Integer, nullable=False, default=100)
    spam_flag_count = Column(Integer, nullable=False, default=0)

    complaints = relationship("Complaint", back_populates="buyer")


# ── Product ──────────────────────────────────────────────────────────────────

class Product(Base):
    __tablename__ = "products"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    price = Column(Integer, nullable=False)
    market_price = Column(Integer, nullable=False)
    # new field to store the local filesystem path of the uploaded image
    image_path = Column(String, nullable=False)
    seller_id = Column(Integer, ForeignKey("sellers.id"), nullable=False)

    seller = relationship("Seller", back_populates="products")


# ── Complaint ────────────────────────────────────────────────────────────────

class Complaint(Base):
    __tablename__ = "complaints"

    id = Column(Integer, primary_key=True, index=True)
    buyer_id = Column(Integer, ForeignKey("buyers.id"), nullable=False)
    seller_id = Column(Integer, ForeignKey("sellers.id"), nullable=False)
    complaint_text = Column(String, nullable=False)
    severity_level = Column(Integer, nullable=False)  # 1–5
    status = Column(String, nullable=False, default="open")  # "open" | "resolved"
    # path to the buyer-uploaded image (optional)
    received_image_path = Column(String, nullable=True)
    # visual similarity score generated by AI (0.0 = perfect match)
    visual_mismatch_score = Column(Float, nullable=True, default=0.0)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))

    buyer = relationship("Buyer", back_populates="complaints")
    seller = relationship("Seller", back_populates="complaints")

    __table_args__ = (
        UniqueConstraint("buyer_id", "seller_id", name="uq_buyer_seller"),
    )
